# Copyright (C) 2023-2026 Swissmakers GmbH
# Author: Michael André Reber
# License: AGPL-3.0-or-later
# https://github.com/getmatinee/matinee
#
# Shows the Sponsor button on this repository

github: getmatinee
ko_fi: matinee
